//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Course
{
	public virtual Collection<Lectures> Lectures
	{
		get;
		set;
	}

	public virtual Collection<Student> Students
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual DateTime StartDate
	{
		get;
		set;
	}

	public virtual DateTime EndDate
	{
		get;
		set;
	}

	public virtual IEnumerable<Lecture> Lecture
	{
		get;
		set;
	}

	public virtual IEnumerable<Student> Student
	{
		get;
		set;
	}

}

