//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;

public class Course
{
    private void Init()
    {
        Lectures = new Collection<Lecture>();
        Students = new Collection<Student>();
    }
    public Course()
    {
        Init();
    }
    public Course(string name)
    {
        Init();
        Name = name;
    }
	public virtual Collection<Lecture> Lectures
	{
		get;
		set;
	}

	public virtual Collection<Student> Students
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual DateTime StartDate
	{
		get;
		set;
	}

	public virtual DateTime EndDate
	{
		get;
		set;
	}
}

