//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;

public class Lecture
{
    public void init()
    {
        Teachers = new Collection<Teacher>();
    }

    public Lecture()
    {
        init();
    }

    public Lecture(string name)
    {
        init();
        Name = name;
    }

	public virtual Collection<Teacher> Teachers
	{
		get;
		set;
	}

	public virtual DateTime StartDate
	{
		get;
		set;
	}

	public virtual DateTime EndDate
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}
}

